# Generated by Django 4.2.17 on 2025-03-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_or_away', models.CharField(choices=[('h', 'Home'), ('a', 'Away')], max_length=1)),
                ('schedule', models.DateTimeField()),
                ('contestant', models.CharField(max_length=100)),
                ('cancelled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='MatchField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('match', models.OneToOneField(limit_choices_to=models.Q(('cancelled', False)), on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='season.match')),
                ('home_goals', models.PositiveSmallIntegerField(default=0)),
                ('away_goals', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='team.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='season.matchfield'),
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(limit_choices_to=models.Q(('start_date__lte', models.F('end_date')), ('end_date__gte', models.F('start_date'))), on_delete=django.db.models.deletion.RESTRICT, to='season.season'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('season', 'schedule')},
        ),
    ]
